### ISSUE TITLE
Exceptions in KSP v1.4

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#48] opened 2018-04-12 12:38 UTC
I'm adding a reference here to the exceptions that TU throws in v1.4. I'm not sure if these have been resolved, but the currently released version still contains them.

----
[ERR 19:17:03.520] Exception handling event OnPartLoaderLoaded in class TexturesUnlimitedLoader:System.NullReferenceException: Object reference not set to an instance of an object
  at KSPShaderTools.TexturesUnlimitedLoader.applyToPartIcons () [0x00000] in <filename unknown>:0 
  at KSPShaderTools.TexturesUnlimitedLoader.onPartListLoaded () [0x00000] in <filename unknown>:0 
  at EventVoid.Fire () [0x00000] in <filename unknown>:0 

[EXC 19:17:03.522] NullReferenceException: Object reference not set to an instance of an object
	KSPShaderTools.TexturesUnlimitedLoader.applyToPartIcons ()
	KSPShaderTools.TexturesUnlimitedLoader.onPartListLoaded ()
	EventVoid.Fire ()
	UnityEngine.Debug:LogException(Exception)
	EventVoid:Fire()
	<CompileAll>c__Iterator0:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by shadowmage45** [comment] 2018-04-12 13:53
Is there any way you could link the config file that is causing these errors to occur?
(I'm not seeing them in my install, so unsure of the cause)

**Comment by Electrocutor** [comment] 2018-04-12 15:42
None needed, just dropping 000_TexturesUnlimited into a clean game causes it. The dll has a DateModified of "Thursday, ‎March ‎22, ‎2018, ‏‎5:11:42 PM".

**Comment by shadowmage45** [comment] 2018-04-12 16:15
Noted -- I'll double check my logs during my next dev session.  I don't remember seeing that problem recently, but it could be something that I've already fixed in the dev version, or simply that I've scrolled past it.

The error would point towards there being an improper config file regarding shaders/shader packs, or more probably, an improper model specified as a target of an icon-shader patch.  Will let you know what I find out.

**Comment by shadowmage45** [comment] 2018-04-13 00:42
I can reproduce the problem on a clean install of KSP 1.4.2 with only ModuleManager and TexturesUnlimited.

I am not seeing the same problem in the current dev versions, in my dev environment.  Strangely -- I -can- duplicate the problem using the dev version in the clean KSP environment; so there must be some other config I have that is 'fixing' it.

**Comment by shadowmage45** [comment] 2018-04-13 00:56
Huh... apparently it is crashing out on one of the stock models that has a null material on one of its transforms.

````

[LOG 18:53:39.184] 2
[LOG 18:53:39.184] 3
[LOG 18:53:39.184] 4
[LOG 18:53:39.184] 5a Particles (UnityEngine.ParticleSystemRenderer)
[LOG 18:53:39.184] 5b Particles (UnityEngine.GameObject)
[LOG 18:53:39.184] 5c    //this line should be the material for the object
[ERR 18:53:39.185] Exception handling event OnPartLoaderLoaded in class TexturesUnlimitedLoader:System.NullReferenceException: Object reference not set to an instance of an object
  at KSPShaderTools.TexturesUnlimitedLoader.applyToPartIcons () [0x00000] in <filename unknown>:0 
  at KSPShaderTools.TexturesUnlimitedLoader.onPartListLoaded () [0x00000] in <filename unknown>:0 
  at EventVoid.Fire () [0x00000] in <filename unknown>:0 
````

Have added a check for null materials and shaders to the code, even though I think that it is technically an error in the prefab/model itself.

**Closed** 2018-04-21 16:28 UTC
Labels: Fixed in Dev, Next Update, bug
