### ISSUE TITLE
Part Hierarchy Bug

### ISSUE THREAD

**Issue by Electrocutor** [shadowmage45/TexturesUnlimited#23] opened 2017-12-11 03:11 UTC
When using the Recolor GUI, it automatically sets all child parts to the same settings as the parent part that you currently have the GUI open for, even when the child part is just a stock part using the standard KSP shader and its own textures, it changes them all to match the parent.

When you actually change views (say launch), then it resets the child back to how it should be, so this is only a problem with GUI itself in the editor.

**Comment by Electrocutor** [comment] 2017-12-11 14:51
I'm going to add to this the TextureSwitch bug as well: it retains the changes when switching between texture options, but at launch or part refresh, it goes back to default+current.

Example:
Tex1: _Color change
Tex2: _Smoothness change
Tex3: _MainTex change

If you cycle through all 3 and stop on Tex3, then you see the effects of all 3 in the editor, but when you launch it only shows the _MainTex change. It should only show the _MainTex change, but in the editor, the switching should revert values to default before applying each Tex to ensure you don't have bleed-over modifiers.

**Comment by shadowmage45** [comment] 2017-12-11 15:39
Ahh, yes, I believe I had seen a bit of this at one point, but wasn't able to duplicate it at the time (the hierarchy issue).  Should be simple enough to clean that up.  I think the exact cause is I'm using `part.transform`, when should be using part.transform.Find("model")  (in the editor, parts are parented directly to eachothers transforms'; in flight they are 'parented' through joints alone)

----

As to the texture options bug -- I'll have to see if I can duplicate the problem with your steps this evening, as I'm not quite sure what you are talking about from reading the text alone.  Certainly not a problem that I've seen in any of my configs.

It sounds like what you are saying is 'it is keeping the properties assigned from the previous texture set, when the current set has no value for that property assigned', which is as intended.  Of course it isn't going to keep those 'cumulative' changes when you launch, as it will only apply the changes for the currently selected texture set.

So, if I'm reading things properly, this is what is happening ?:
* Default: Texture Set A - Specifies 'smoothness' of 0.5.
* switch to: Texture Set B - Specifies 'metal' value of 0.5, no smoothness specified, so the 0.5 from previous set carries over.
* switch to: Texture Set C - Specifies neither smoothness, nor metal.  Defaults of 1.0 are expected, but the previous 0.5 values are carried over -in the editor only- from the previously examined texture sets.

Really not sure how _I_ am going to solve that, if it is what I'm thinking.  Basically if you manipulate a property through any texture set for a part, you need to adjust that property for **all** texture sets.

The 'keep existing values' setup is really only intended/useful for the 'default-shader-assignment' use -- when using in-game texture switching you must consistently use all properties in every texture set that will at any point be different than the default values for those properties.  That is part of defining a texture set--ensuring all properties are specified as they should be for that texture set.

Any change to the texture-set functionality (to enforce defaults for undefined properties) will break the 'default-shader-assignment' functionality.

**Comment by Electrocutor** [comment] 2017-12-11 15:51
The place where this comes into play most is when you assume that it will use default values, for example 1.0 multiplier on _Metal and _Smoothness. When actually used it does, but when switching between them, you have to manually specify 1.0 for both if you want it to show up correctly while in the editor and switching between options.

I would assume the solution would be to revert to the values of a fresh prefab, then apply whatever the current textureset is (which is exactly what it will do at launch).

**Comment by shadowmage45** [comment] 2017-12-12 00:36
>I would assume the solution would be to revert to the values of a fresh prefab, then apply whatever the current textureset is (which is exactly what it will do at launch).

I have no guarantee that the models/meshes on the prefab correspond to the currently selected models/meshes in the part.  In fact, in SSTU, it is most often different due to the model/mesh switching implemented everywhere.

I understand what you are asking for, and agree that it would make for an easier time writing configs, I'm just not sure if it can be done (easily/without breaking other things).

Will give this particular bit some more thought... I might be able to come up with something that doesn't break other already in-use features.

For now, the functional/working setup for this is to specify every parameter in every texture set if even a single texture set adjusts it away from the default.  Yes, it is less than ideal (from a config-writing perspective), but it does function.

**Comment by shadowmage45** [comment] 2017-12-17 18:01
Please open a new ticket regarding the 'default parameter values' problem -- will still see what I can do about cleaning that up.

**Comment by Electrocutor** [comment] 2017-12-17 18:05
You mean the part where values bleed from one TextureSet to the next instead of reverting first to initial values?

**Comment by shadowmage45** [comment] 2017-12-17 18:15
Yep, that one :)

**Comment by Electrocutor** [comment] 2017-12-19 02:26
The part hierarchy has not been fixed in 1.0.0.6. When setting a parent part, the child parts still show the same change in the editor.

**Comment by shadowmage45** [comment] 2017-12-19 02:50
Can you provide the steps to duplicate the problem please, as I was unable to duplicate it in my testing.

**Comment by Electrocutor** [comment] 2017-12-19 17:41
The problem is present using any shader with any properties and is reproducible in all cases.

1. Vanilla KSP + TU
2. Create any CFG that uses KSPTextureSwitch
3. Change Texture on a parent part

Example:
https://imgur.com/a/Wc30M

@REFLECTION_CONFIG[default]
{
	%enabled = true
}

@PART[landerCabinSmall]
{
	MODULE
	{
		name = KSPTextureSwitch
		currentTextureSet = Default
		
		TEXTURESET
		{
			name = Default
		}
		TEXTURESET
		{
			name = Metal
		}
	}
}

KSP_TEXTURE_SET
{
	name = Default

	TEXTURE
	{
		shader = SSTU/PBR/StockMetallicBumped

		PROPERTY
		{
			name = _Metal
			float = 0.0
		}
		PROPERTY
		{
			name = _Smoothness
			float = 1.0
		}
	}
}

KSP_TEXTURE_SET
{
	name = Metal

	TEXTURE
	{
		shader = SSTU/PBR/Metallic

		PROPERTY
		{
			name = _Metal
			float = 0.75
		}
		PROPERTY
		{
			name = _Smoothness
			float = 0.75
		}
	}
}

**Comment by shadowmage45** [comment] 2017-12-20 00:12
Ahh.. wonderful Unity again.  Gawd, I need to get away from this game-engine... it is so terrible.  (well, half of the problems are just how KSP is using it...improperly...with giant collections of hacks holding things together, with inconsistent use of the engine features)

Should be fixed in the upcoming release.
![screenshot4](https://user-images.githubusercontent.com/1503399/34184908-aee9a3ca-e4df-11e7-9669-fc419aa4a824.png)

![screenshot5](https://user-images.githubusercontent.com/1503399/34184910-b0544d3c-e4df-11e7-84d6-dae0d7a50baf.png)

**Closed** 2017-12-20 00:19 UTC
Labels: bug, Fixed in Dev, Next Update
